# Generated by Django 5.0.2 on 2024-02-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Forum', '0003_question_downvote_alter_question_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='downvote',
        ),
    ]
