# Generated by Django 4.2.7 on 2024-04-01 03:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Forum', '0006_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='upvoted_comments', to=settings.AUTH_USER_MODEL),
        ),
    ]
