# Generated by Django 4.2.7 on 2024-04-16 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0004_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='server_profile'),
        ),
    ]
