# Generated by Django 4.2.7 on 2024-04-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0005_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='unique_id',
            field=models.CharField(default='f372fa', max_length=6, unique=True),
        ),
    ]
