# Generated by Django 4.2.7 on 2024-04-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Community', '0006_room_unique_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='unique_id',
            field=models.CharField(default='dc0c42', max_length=6, unique=True),
        ),
    ]
